name: elim_trust_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Please verify your Dart SDK version with `flutter --version` and adjust if needed.
  sdk: '>=3.3.0 <4.0.0' # Make sure this is in quotes

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.6
  webview_windows: ^0.4.0
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.3
 

  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.1

  open_file: ^3.5.10
  share_plus: ^11.0.0
  
  http: ^1.4.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Using latest stable version. ^3.0.0 is also a common choice.
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - pdf/
